name: Deploy

on:
  push:
    branches: [develop]
  repository_dispatch:
    types: [deploy]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1
  ECR_URI: ${{ secrets.ECR_URI }}
  REGION: us-east-1
  ENVIRONMENT: dev

jobs:
  build_ui:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: cset-analytics-ui
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: cisagov/cset-analytics-ui
      - name: Get Tag
        id: vars
        run: echo ::set-output name=tag::$(git rev-parse --short HEAD)
      - name: Build Docker Image
        run: docker build -t $IMAGE_REPO:${{steps.vars.outputs.tag}} .
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}
      - name: Tag Docker Image
        run: docker tag $IMAGE_REPO:${{steps.vars.outputs.tag}} $ECR_URI/$IMAGE_REPO:${{steps.vars.outputs.tag}}
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}
      - name: ECR Login
        run: aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URI/$IMAGE_REPO
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}
      - name: Push Docker Image
        run: docker push $ECR_URI/$IMAGE_REPO:${{steps.vars.outputs.tag}}
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}

  build_api:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: cset-analytics-api
    outputs:
      tag: ${{ steps.vars.outputs.tag}}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: cisagov/cset-analytics-api
      - name: Get Tag
        id: vars
        run: echo ::set-output name=tag::$(git rev-parse --short HEAD)
      - name: Build Docker Image
        run: docker build -t $IMAGE_REPO:${{steps.vars.outputs.tag}} .
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}
      - name: Tag Docker Image
        run: docker tag $IMAGE_REPO:${{steps.vars.outputs.tag}} $ECR_URI/$IMAGE_REPO:${{steps.vars.outputs.tag}}
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}
      - name: ECR Login
        run: aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URI/$IMAGE_REPO
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}
      - name: Push Docker Image
        run: docker push $ECR_URI/$IMAGE_REPO:${{steps.vars.outputs.tag}}
        if: ${{ github.event.client_payload.trigger == env.IMAGE_REPO }}

  terraform:
    runs-on: ubuntu-latest
    needs: [build_ui, build_api]

    steps:
      # Checkout cicd repo for running terraform
      - uses: actions/checkout@v2

      # Install Terraform
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.3
      - name: Verify Terraform version
        run: terraform --version
      # Initialize Terraform
      - name: Terraform init
        working-directory: ./terraform
        run: terraform init -input=false

      # Select terraform workspace
      - name: Terraform Workspace
        working-directory: ./terraform
        run: |
          terraform workspace select $ENVIRONMENT
          terraform workspace show

      # Validate Terraform
      - name: Terraform validation
        working-directory: ./terraform
        run: terraform validate

      # Sometimes this just needs run again...
      - name: Terraform init 2
        working-directory: ./terraform
        run: terraform init -input=false

      # Plan terraform
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -input=false -var-file ./vars/$ENVIRONMENT.tfvars -var="api_image_tag=${{needs.build_api.outputs.tag}}" -var="ui_image_tag=${{needs.build_ui.outputs.tag}}"


      # Apply terraform
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -input=false -auto-approve -var-file ./vars/$ENVIRONMENT.tfvars -var="api_image_tag=${{needs.build_api.outputs.tag}}" -var="ui_image_tag=${{needs.build_ui.outputs.tag}}"
